### ISSUE TITLE
plasmid/phage genomes

### ISSUE THREAD

**Issue by seajane** [labgem/PPanGGOLiN#82] opened 2022-04-27 02:29 UTC
I am trying to annotate some short sequences and get the error message:
 
`Error:  Sequence must be 20000 characters (only 7528 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)`

However there is no -p meta option for `annotate`:
`ppanggolin: error: unrecognized arguments: -p`

**Comment by jpjarnoux** [comment] 2022-04-27 07:18
Hi
For me, it's an error from a dependency, and I think about prodigal in this case. For PPanGGOLiN, the `-p` option it's to give the pangenome. Could you please launch again your ppanggolin command with at the end `--verbose 2` to see more information and post here the result ?
Thanks

**Comment by seajane** [comment] 2022-04-27 22:14
Thanks for looking into this! Here's the log file output:

`2022-04-27 15:02:14 main.py:l214 INFO	Command: /Users/hbouzek/opt/anaconda3/envs/ppanggolin/bin/ppanggolin annotate --fasta plasmids.txt -o ppgg3 --verbose 2 --log stdout.txt
2022-04-27 15:02:14 main.py:l215 INFO	PPanGGOLiN version: 1.2.74
2022-04-27 15:02:14 annotate.py:l473 INFO	Reading plasmids.txt the list of organism files
2022-04-27 15:02:14 annotate.py:l485 INFO	Annotating 40 genomes using 1 cpus...
2022-04-27 15:02:21 annotate.py:l495 INFO	Done annotating genomes
2022-04-27 15:02:21 writeBinaries.py:l648 INFO	Writing genome annotations...
2022-04-27 15:02:21 writeBinaries.py:l666 INFO	writing the protein coding gene dna sequences
2022-04-27 15:02:21 writeBinaries.py:l711 INFO	Done writing the pangenome. It is in file : ppgg3/pangenome.h5`

**Here's the verbose output:**

`Error:  Sequence must be 20000 characters (only 17483 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 6032 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 15299 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11935 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11483 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 14216 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 14924 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 6307 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13747 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11748 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13920 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 8884 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13930 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11182 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13143 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13159 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 6308 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11502 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 10680 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 6333 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 9503 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 10601 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 8281 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 14286 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 16796 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 10856 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 14386 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 11357 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 7108 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 7129 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 13746 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 3909 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 10845 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 19405 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 6285 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 4956 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Error:  Sequence must be 20000 characters (only 14401 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)
Warning:  ideally Prodigal should be given at least 100000 bases for training.
You may get better results with the -p meta option.
Error:  Sequence must be 20000 characters (only 7528 read).
(Consider running with the -p meta option or finding more contigs from the same genome.)'

Here's the info from the h5 file after annotation:
`Genes : 272
Organisms : 40`

**Comment by jpjarnoux** [comment] 2022-04-28 12:22
I confirm that's not a bug from PPanGGOLiN, but a problem with prodigal. I will try to make an enhancement in PPanGGOLiN to prevent this issue.

**Comment by jpjarnoux** [comment] 2022-04-29 12:28
I made a quick fix. Now, there is the option `--prodigal_procedure` alias `-p` to force the `meta` or `single` procedure. I also add an automatic choice by PPanGGOLiN in function of the contig length, but I didn't test this part. Let me know if you have any trouble.
To test the enhancement : 
```
#if you already clone ppanggolin git
cd path/to/ppanggolin/directory
#if you don't 
git clone https://github.com/labgem/PPanGGOLiN.git
cd PPanGGOLiN
#After
git fetch
git checkout 82-plasmidphage-genomes
pip install .
# Now you can test the command, it should be the 1.2.92 version of PPanGGOLiN
```

**Comment by jpjarnoux** [comment] 2022-05-09 09:23
Hi,
There was a small bug in the automatic choice. I think in your case nothing was impacted, but to be sure, you can update again with the same commands as before. Sorry for that.
Jérôme

**Comment by clb21565** [comment] 2022-12-10 17:28
have you pushed the most recent version with this fix to conda yet? 
just asking as i did the default conda installation and got v 1.2.7 something and this option wasn't there
thank you for the great tool!

**Comment by axbazin** [comment] 2022-12-10 19:58
It's not in a release available through conda yet, sorry.

It's quite curious that only parts of ppanggolin got updated by your 'pip install .' though.

**Comment by clb21565** [comment] 2022-12-11 01:19
I'd say so too! 

this is the thing from ppanggolin workflow -h 

usage: ppanggolin workflow [-h] [--fasta FASTA] [--anno ANNO]
                           [--clusters CLUSTERS] [-o OUTPUT]
                           [--basename BASENAME] [--mode {0,1,2,3}]
                           [--coverage COVERAGE] [--identity IDENTITY]
                           [--rarefaction] [-K NB_OF_PARTITIONS] [--no_defrag]
                           [--tmpdir TMPDIR] [--verbose {0,1,2}] [--log LOG]
                           [-d] [-c CPU] [-f]

attempting to pass -p meta gives an error. Running ppanggolin workflow on the data errors on contigs < 20,000 bp. 

ppanggolin -v : 

ppanggolin 1.2.96

ppanggolin annotate -h : 

usage: ppanggolin annotate [-h] [--fasta FASTA] [--anno ANNO] [-o OUTPUT]
                           [--overlap] [--norna]
                           [--kingdom {bacteria,archaea}]
                           [--translation_table TRANSLATION_TABLE]
                           [--basename BASENAME] [--use_pseudo]
                           [-p {single,meta}] [--tmpdir TMPDIR]
                           [--verbose {0,1,2}] [--log LOG] [-d] [-c CPU] [-f]

**Comment by axbazin** [comment] 2022-12-13 15:45
Ah, actually the option is only available through the 'annotate' subcommand, as 'workflow' is specifically for 'non customizable runs", so it all makes sense.

To get your pangenome you'll have to go through the step-by-step process if you want to use that option, I'm afraid.

**Comment by axbazin** [comment] 2023-02-15 16:53
Closing as this is now in master and soon in the next release

**Closed by axbazin** 2023-02-15 16:53 UTC
Labels: enhancement
