### ISSUE TITLE
issue with ppanggolin cluster

### ISSUE THREAD

**Issue by cmonat** [labgem/PPanGGOLiN#86] opened 2022-06-08 12:36 UTC
Hello,

I'm trying to run ppanggolin cluster on the pangenome.h5 that was generated before combining fasta and gff files and I ran into the following error:

`>ppanggolin cluster -p pangenome.h5
2022-06-08 08:20:06 main.py:l214 INFO   Command: /grid/sw/ppanggolin/1.2.74/bin/ppanggolin cluster -p pangenome.h5
2022-06-08 08:20:06 main.py:l215 INFO   PPanGGOLiN version: 1.2.74
2022-06-08 08:20:06 readBinaries.py:l39 INFO    Getting the current pangenome's status
2022-06-08 08:20:06 readBinaries.py:l83 INFO    Extracting and writing CDS sequences from a .h5 pangenome file to a fasta file...
0gene [00:00, ?gene/s]
2022-06-08 08:20:06 cluster.py:l212 INFO        Clustering all of the genes sequences...
2022-06-08 08:20:06 cluster.py:l48 INFO Creating sequence database...
The input files have no entry:  - /tmp/28749866.1.all.q/tmp1vxhkr52/nucleotid_sequences
Please check your input files. Only files in fasta/fastq[.gz|bz2] are supported
Traceback (most recent call last):
  File "/grid/sw/ppanggolin/1.2.74/bin/ppanggolin", line 11, in <module>
    load_entry_point('ppanggolin==1.2.74', 'console_scripts', 'ppanggolin')()
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/main.py", line 219, in main
    ppanggolin.cluster.launch(args)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/cluster/cluster.py", line 324, in launch
    clustering(pangenome, args.tmpdir, args.cpu, defrag=not args.no_defrag, code=args.translation_table,
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/cluster/cluster.py", line 213, in clustering
    rep, tsv = firstClustering(sequenceFile, newtmpdir, cpu, code, coverage, identity, mode)
  File "/grid/sw/ppanggolin/1.2.74/lib/python3.8/site-packages/ppanggolin-1.2.74-py3.8-linux-x86_64.egg/ppanggolin/cluster/cluster.py", line 49, in firstClustering
    subprocess.run(cmd, stdout=subprocess.DEVNULL, check=True)
  File "/grid/sw/python/3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createdb', '/tmp/28749866.1.all.q/tmp1vxhkr52/nucleotid_sequences', '/tmp/28749866.1.all.q/tmp1vxhkr52/nucleotid_sequences_db']' returned non-zero exit status 1.
`
I checked the fasta files are right.
Do you have any idea what I should do to make it work?

Thank you in advance
Regards
C.

**Comment by cmonat** [comment] 2022-06-09 09:14
Hello,

by "combining fasta and gff files " I mean that I used the command using both option --anno and --fasta.
The result of the info command is here:
genomes annotated : true
genes clustered : false
genes have their sequences : true
gene families have their sequences : false
neighbors graph : false
pangenome partitioned : false
RGP predicted : false
Spots predicted : false
Modules predicted : false
PPanGGOLiN version : 1.2.74
annotation
    used_local_identifiers : True
    read_pseudogenes : False
    read_annotations_from_file : True

Thanks for your help
C.

**Comment by axbazin** [comment] 2022-06-09 09:58
Thank you, indeed everything seems to have been loaded correctly.
There might be some trickery with the gff identifiers, I've had troubles akin to this because of special characters in the gene IDs in gff files in the past, but I am not certain this is it.

Is it possible for you to share some of your fasta/gff so that I can reproduce the bug and see what is wrong ?

**Comment by cmonat** [comment] 2022-06-09 10:06
I'll ask my supervisor and let you know asap.
Thanks a lot
C.

**Comment by cmonat** [comment] 2022-06-13 12:48
Hello,

sorry I cannot share any files.
What kind of trickery thing should I expect in the GFF identifier?
Thanks anyway

Have a nice day
Regards
C.

**Comment by axbazin** [comment] 2022-06-13 13:13
Any non alphanumeric character could cause a problem, so if you have some you can attempt to change those ids. I have had trouble with "|" in the ids before but those should work fine in the current version.

What's happenning concretely here is that mmseqs2 (one of ppanggolin dependencies) fails to read the .fasta files. So either they are not read properly by ppanggolin when loading up the annotations and the sequences, but it seems to have gone relatively well since it thinks that everything is fine, or they are not read as expected by mmseqs which can happen with non-alphanumeric identifiers, or with sequences with unexpected characters for example.

I can still try to help out if you can tell me how you generated the .gff and the .fasta file.
Is it a public workflow like prokka, pgap or bakta ?
Otherwise if it is an in-house workflow, maybe you can run it on a small subset of public genomes ? If it generates the same error maybe those could be shared.

Adelme

**Comment by axbazin** [comment] 2022-06-17 15:07
Great! Good luck in your analysis.

**Comment by axbazin** [comment] 2023-04-20 13:59
Hello,

Most likely it's related to a non-expected nucleotide character in the gene sequences or gene identifiers. The error comes from mmseqs createdb, it's probably easier for me to find out if you can send a few files.

If you still cannot send out a few files so that I can try to find the reason myself, the best path that you have is to try to execute mmseqs createdb on all gene nucleotide sequences of the genomes of your pangenome (I don't remember if bakta outputs such files?) and see what mmseqs outputs as error.

Good luck!
Adelme

**Comment by cmonat** [comment] 2023-04-20 14:00
Ok, thanks for your help.
I cannot share the files so I will execute mmseqs myself and see what I get.
Thanks :)
C.

**Comment by axbazin** [comment] 2023-05-02 14:03
Hello,

Did you manage to solve your problem?

Adelme

**Comment by cmonat** [comment] 2023-05-10 07:15
Hello,

I have try to run mmseqs but it seems to have not problem, so finally we have rerun the gff files with another pipeline and now it seems to be ok for the step I described earlier. BUT ^^ now I have a new trouble with mmseqs search:


```bash
2023-05-09 11:15:18 cluster.py:l34 INFO Aligning cluster representatives...
Can not write to data file /tmp/32218836.1.all.q/tmp8t8_pjkz/10578038853214095674/pref_0.34
Can not write to data file /tmp/32218836.1.all.q/tmp8t8_pjkz/10578038853214095674/pref_0.32
Traceback (most recent call last):
  File "/grid/sw/ppanggolin/1.2.96/bin/ppanggolin", line 11, in <module>
    load_entry_point('ppanggolin==1.2.96', 'console_scripts', 'ppanggolin')()
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/main.py", line 183, in main
    ppanggolin.workflow.all.launch(args)
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/workflow/all.py", line 55, in launch
    clustering(pangenome, args.tmpdir, args.cpu, identity=args.identity, coverage=args.coverage, mode=args.mode,
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/cluster/cluster.py", line 232, in clustering
    aln = align_rep(rep, newtmpdir, cpu, coverage, identity)
  File "/grid/sw/ppanggolin/1.2.96/lib/python3.8/site-packages/ppanggolin-1.2.96-py3.8-linux-x86_64.egg/ppanggolin/cluster/cluster.py", line 35, in align_rep
    subprocess.run(cmd, stdout=subprocess.DEVNULL, check=True)
  File "/grid/sw/python/3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'search', '/tmp/32218836.1.all.q/tmp8t8_pjkz/rep_sequence_db', '/tmp/32218836.1.all.q/tmp8t8_pjkz/rep_sequence_db', '/tmp/32218836.1.all.q/tmp8t8_pjkz/rep_alignment_db', '/tmp/32218836.1.all.q/tmp8t8_pjkz', '-a', '--min-seq-id', '0.8', '-c', '0.8', '--cov-mode', '1', '--threads', '40']' returned non-zero exit status 1.
```

is this error also coming from mmseqs and not PPanGGOLiN itself? Any idea how to solve it?
Thanks a lot
C.

**Comment by axbazin** [comment] 2023-05-10 07:26
Hello,

This error is raised during the mmseqs2 step, but it is very likely related to your work environment.
The software prompts the following 2 lines:
Can not write to data file /tmp/32218836.1.all.q/tmp8t8_pjkz/10578038853214095674/pref_0.34
Can not write to data file /tmp/32218836.1.all.q/tmp8t8_pjkz/10578038853214095674/pref_0.32

Which tells that either there is no more space on the device, or it does not have the capability to write what it wants in this folder, or something equivalent.

Adelme

**Comment by cmonat** [comment] 2023-05-11 11:25
Hello,

is it possible to specify a tmp directory for mmsesq through ppanggolin command?
If yes, I was not able to find it in the documentation. If not, would it be possible to change that?
Thanks a lot

C.

**Comment by axbazin** [comment] 2023-05-11 17:32
Hello,
If I'm not mistaken, by changing PPanGGOLiN's temporary directory it will change MMseqs2 temporary directory as well, so that should be the "--tmpdir" option.

I had a similar problem in the past (full disk during MMseqs2 execution, when computing a big pangenome) and I just solved it by writing the tmpdir to a bigger partition.

Adelme

**Comment by cmonat** [comment] 2023-05-12 07:15
Ok, thanks I'll try that :)
C.

**Comment by jpjarnoux** [comment] 2023-10-13 08:33
Hello,
I will close this issue, as it seems you no longer have a problem.
Don't hesitate to reopen if you need further assistance.
Jérôme

**Closed by jpjarnoux** 2023-10-13 08:33 UTC
